language: ruby
rvm:
  - 2.4.2

services:
  - postgresql '9.5'

before_script:
  - psql -c "create user shrindex;" -U postgres
  - psql -c "create database shrindex_testing OWNER shrindex;" -U postgres
  - psql -c "alter user shrindex CREATEDB;" -U postgres

