language: ruby
rvm:
  - 2.5.1
  - 2.6.3

addons:
  postgresql: 9.5

services:
  - redis-server

before_install:
  - yes | gem update --system --force
  - gem install bundler

before_script:
  - psql -c "create user shrindex;" -U postgres
  - psql -c "create database shrindex_testing OWNER shrindex;" -U postgres
  - psql -c "alter user shrindex CREATEDB;" -U postgres
  - bundle exec rails db:migrate RAILS_ENV=test


