#!/bin/sh

set -e

bundle_check() {
    bundle check || bundle install
}

case $1 in
    start) 
        bundle_check
        rm -f tmp/pids/server.pid
        exec bundle exec rails server -b 0.0.0.0
        ;;
    test)
        bundle check
        exec bundle exec rails test
        ;;
    update)
        exec bundle update
        ;;
    console)
        bundle_check
        exec bundle exec rails console
        ;;
    shell)
        exec /bin/bash
        ;;
    *)
        exec $@
        ;;
esac
