# This is the default database.yml; it should not be used on a real
# server, which should overwrite this file with one suited to the
# environment under which it is running
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

# Some values that can be set are commented out
# because, when running under Vagrant, we use UNIX socket connections
# and 'ident' authorization, which requires no password
development: &vagrant
  adapter: postgresql
  encoding: unicode
  # see config/boot.rb
  <% unless TRLN::IngestEnvironment.vagrant? %>
  # host/passwd not needed when postgres is on localhost and ident auth
  # is available, as with vagrant setup
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  password: <%= ENV['DB_PASSWORD'] %>
  <% end %>
  
  database: <%= ENV['DB_NAME'] || 'shrindex' %>
  pool: <%= ENV.fetch('DB_POOL', 5) %>
  reaping_frequency: <%= ENV.fetch('DB_REAP_FREQ', 10) %>
  username: <%= ENV['DB_USER'] || 'set_env_vars' %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: shrindex_testing
  host: localhost
  port: 5432
  pool: 1
  username: postgres 
  password: <%= ENV.fetch('APP_POSTGRES_PASSWORD', '<fakepassword>') %>

production:
  <<: *vagrant
