common:  &common
  url: 
    - http://localhost:8983/solr/
  collections:
    - trlnbib
    - icetocs

test:
    <<: *common

development:
    <<: *common
    collections:
      shared: trln-dev
      ice_tocs: icetocs-dev
    
production:
    <<: *common
    #url:
    #  - http://solr_1:8983/solr/
    #  - http://solr_2:8983/solr/
    #  - http://solr_3:8983/solr/
  
