# url is an array of Solr URLs; most Solr operations
# will take a random URL from among those provided.
# see app/services/solr_service.rb
common:  &common
  url: 
    - <%= ENV.fetch('SOLR_URL', 'http://localhost:8983/solr/') %>
  collections:
    - trlnbib
    - icetocs

test:
    <<: *common

development:
    <<: *common
    collections:
      shared: trln-dev
      ice_tocs: icetocs-dev
    
production:
    <<: *common
    #url:
    #  - http://solr_1:8983/solr/
    #  - http://solr_2:8983/solr/
    #  - http://solr_3:8983/solr/
  
