name: CI

on:
  push:
  pull_request:

    services:
      db:
        image: postgres:9.5
        ports:
          - 5432:5432  
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5      

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.5.1, 2.6.3 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'    
    - name: Build and test with Rake
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails test
